# Generated by Django 6.0.3 on 2026-05-03 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_seed_music_providers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'manual'), ('scheduled', 'scheduled'), ('retry', 'retry')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('partial', 'partial'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('matched_tracks', models.PositiveIntegerField(default=0)),
                ('added_tracks', models.PositiveIntegerField(default=0)),
                ('skipped_tracks', models.PositiveIntegerField(default=0)),
                ('failed_tracks', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'sync_jobs',
            },
        ),
        migrations.CreateModel(
            name='ExternalTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_track_id', models.CharField(max_length=255)),
                ('external_album_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(max_length=500)),
                ('artists', models.JSONField(default=list)),
                ('normalized_artists', models.CharField(blank=True, max_length=1000)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('isrc', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='external_tracks', to='integrations.musicprovider')),
            ],
            options={
                'db_table': 'external_tracks',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_playlist_id', models.CharField(max_length=255)),
                ('owner_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, null=True)),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('snapshot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='integrations.externalaccount')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='playlists', to='integrations.musicprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('external_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='sync.externaltrack')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='sync.playlist')),
            ],
            options={
                'db_table': 'playlist_tracks',
            },
        ),
        migrations.CreateModel(
            name='SyncJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('add', 'add'), ('remove', 'remove'), ('skip', 'skip'), ('noop', 'noop'), ('conflict', 'conflict')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped'), ('conflict', 'conflict'), ('missing', 'missing')], default='pending', max_length=20)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync.syncjob')),
                ('source_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sync_items', to='sync.externaltrack')),
                ('target_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_sync_items', to='sync.externaltrack')),
            ],
            options={
                'db_table': 'sync_job_items',
            },
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('one_way', 'one_way'), ('two_way', 'two_way')], default='one_way', max_length=20)),
                ('mode', models.CharField(choices=[('append_only', 'append_only'), ('mirror', 'mirror')], default='append_only', max_length=20)),
                ('conflict_policy', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual'), ('skip', 'skip')], default='manual', max_length=20)),
                ('missing_track_policy', models.CharField(choices=[('skip', 'skip'), ('create_conflict', 'create_conflict')], default='create_conflict', max_length=30)),
                ('schedule_type', models.CharField(choices=[('manual', 'manual'), ('interval', 'interval'), ('cron', 'cron')], default='manual', max_length=20)),
                ('schedule_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sync_rules', to='integrations.externalaccount')),
                ('source_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sync_rules', to='sync.playlist')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_sync_rules', to='integrations.externalaccount')),
                ('target_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_sync_rules', to='sync.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_rules',
            },
        ),
        migrations.AddField(
            model_name='syncjob',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sync.syncrule'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(max_length=500)),
                ('artists', models.JSONField(default=list)),
                ('normalized_artists', models.CharField(blank=True, max_length=1000)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('isrc', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tracks',
                'indexes': [models.Index(fields=['isrc'], name='idx_tracks_isrc'), models.Index(fields=['normalized_title'], name='idx_tracks_norm_title')],
            },
        ),
        migrations.AddField(
            model_name='externaltrack',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_tracks', to='sync.track'),
        ),
        migrations.CreateModel(
            name='MappingCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('candidate', 'candidate'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='candidate', max_length=20)),
                ('confirmed_by_user', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_candidates_from', to='sync.externaltrack')),
                ('target_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_candidates_to', to='sync.externaltrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mapping_candidates',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_mapping_candidates_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_track', 'target_track'), name='uq_mapping_candidate_user_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'provider'], name='idx_playlists_user_provider'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['external_playlist_id'], name='idx_playlists_external_id'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('external_account', 'external_playlist_id'), name='uq_playlist_account_external_id'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['playlist', 'position'], name='idx_playlist_tracks_position'),
        ),
        migrations.AddIndex(
            model_name='syncjobitem',
            index=models.Index(fields=['job', 'status'], name='idx_sync_job_items_status'),
        ),
        migrations.AddIndex(
            model_name='syncrule',
            index=models.Index(fields=['user', 'is_active'], name='idx_sync_rules_user_active'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['rule', 'status'], name='idx_sync_jobs_rule_status'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['created_at'], name='idx_sync_jobs_created_at'),
        ),
        migrations.AddIndex(
            model_name='externaltrack',
            index=models.Index(fields=['provider', 'isrc'], name='idx_ext_tracks_provider_isrc'),
        ),
        migrations.AddIndex(
            model_name='externaltrack',
            index=models.Index(fields=['normalized_title'], name='idx_ext_tracks_norm_title'),
        ),
        migrations.AddConstraint(
            model_name='externaltrack',
            constraint=models.UniqueConstraint(fields=('provider', 'external_track_id'), name='uq_external_track_provider_id'),
        ),
    ]
