# Generated by Django 6.0.3 on 2026-04-27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("api_base_url", models.TextField(blank=True, null=True)),
                ("supports_oauth", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "music_providers",
            },
        ),
        migrations.CreateModel(
            name="ExternalAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_user_id", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(choices=[("active", "active"), ("need_reauth", "need_reauth"), ("error", "error"), ("revoked", "revoked"), ("disabled", "disabled")], default="active", max_length=20)),
                ("access_token_encrypted", models.BinaryField(blank=True, null=True)),
                ("refresh_token_encrypted", models.BinaryField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ("metadata", models.JSONField(default=dict)),
                ("last_reauthorized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="integrations.musicprovider")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "external_accounts",
                "unique_together": {("user", "provider", "external_user_id")},
            },
        ),
    ]
